.libPaths("~/R/x86_64-pc-linux-gnu-library/4.5")
options(repos = c(CRAN = "https://cloud.r-project.org"), Ncpus = 4)
BiocManager::install("impute", ask = FALSE, update = FALSE)
install.packages("samr")
try(remotes::install_github("metaOmics/MetaDE", upgrade = "never"))
try(install.packages("https://cran.r-project.org/src/contrib/Archive/COCONUT/COCONUT_1.0.2.tar.gz", repos = NULL, type = "source"))
cat("\n=== FINAL STATUS ===\n")
for (p in c("impute","samr","MetaDE","COCONUT"))
  cat(sprintf("%-10s %s\n", p, if (requireNamespace(p, quietly=TRUE)) "OK" else "MISSING"))
