# ============================================================
# Phase 1: which MMR implementation produced the published numbers?
#
# Target: d_plot_Type_I_error_small.rda, a Figure 1 input, produced by
# Unbalanced_Type_I_small.R from sim_unbalanced_type1_small.rda, which is
# generated by data_simulation_unbalanced.R (m=20, n_DE=0, seeds 101:200).
# The generator is deterministic given the seed, so we can regenerate the
# exact dataset and see which implementation reproduces the stored value.
#
# Variants:
#   A  integration_comparison* : for(i in 1:ncol(d_seq)) -> only first 4m genes
#   B  2026 scripts            : sweep over all genes, coefficients on RAW seq
#   C  scale-fixed             : same coefficients applied to log(seq+1)
#   D  direction+scale correct : MM(log(seq+1), array), applied to log(seq+1)
# ============================================================
.libPaths(c("~/R/x86_64-pc-linux-gnu-library/4.5", .libPaths()))
ROOT <- "/work/users/x/u/xuejun1/Integration_paper_Sim"
SIM  <- file.path(ROOT, "simulation_2024")
MMRD <- file.path(ROOT, "Cross-Platform-Normalization-master/MatchMixeR/R")
setwd(SIM)
suppressPackageStartupMessages({ library(stringr) })

# ---- 1. the real generator, extracted verbatim (lines 838-1006) ----------
gen_src <- readLines("data_simulation_unbalanced.R")[838:1006]
# only change: the hardcoded OneDrive path to the seed dataset
gen_src <- sub('load\\(".*sim_BMI_control0\\.rda"\\)',
               sprintf('load("%s")', file.path(ROOT, "sim_BMI_control0.rda")), gen_src)
eval(parse(text = paste(gen_src, collapse = "\n")))
stopifnot(is.function(sim_array_seq_conditions))

# ---- 2. the real scorer, extracted verbatim from the consumer -----------
cons <- readLines("Unbalanced_Type_I_small.R")
s <- grep("^Type_I_error_Power <- function", cons)[1]
# find the closing brace by balancing, not by the first "}" (which is a loop's)
bal <- 0; e <- NA
for (k in s:length(cons)) {
  txt <- gsub("#.*$", "", cons[k])
  bal <- bal + lengths(regmatches(txt, gregexpr("\\{", txt))) -
               lengths(regmatches(txt, gregexpr("\\}", txt)))
  if (k > s && bal == 0) { e <- k; break }
}
stopifnot(!is.na(e))
eval(parse(text = paste(cons[s:e], collapse = "\n")))
stopifnot(is.function(Type_I_error_Power))
cat("scorer: lines", s, "-", e, "\n")

# ---- 3. MatchMixeR ------------------------------------------------------
owd <- getwd(); setwd(MMRD)
for (f in c("ckmeans.R","dwd.R","eb.R","functions.R","gq.R","MatchMixeR.R","xpn.R")) source(f)
setwd(owd)

# ---- 4. the four variants ----------------------------------------------
variants <- list(
  A_asis_loop_rawseq = function(d_array, d_seq) {
    mm <- MM(as.matrix(d_array), as.matrix(log(d_seq + 1)))
    b0 <- mm$betamat[,1] + mm$betahat[1]; b1 <- mm$betamat[,2] + mm$betahat[2]
    ds <- d_seq
    for (i in 1:ncol(d_seq)) ds[i, ] <- b0[i] + b1[i] * as.numeric(d_seq[i, ])
    ds
  },
  B_sweep_rawseq = function(d_array, d_seq) {
    mm <- MM(as.matrix(d_array), as.matrix(log(d_seq + 1)))
    b0 <- mm$betamat[,1] + mm$betahat[1]; b1 <- mm$betamat[,2] + mm$betahat[2]
    sweep(sweep(d_seq, 1, b1, "*"), 1, b0, "+")
  },
  C_sweep_logseq = function(d_array, d_seq) {
    mm <- MM(as.matrix(d_array), as.matrix(log(d_seq + 1)))
    b0 <- mm$betamat[,1] + mm$betahat[1]; b1 <- mm$betamat[,2] + mm$betahat[2]
    sweep(sweep(log(d_seq + 1), 1, b1, "*"), 1, b0, "+")
  },
  D_correct_direction = function(d_array, d_seq) {
    # map seq -> array space, which is the direction the rest of the paper uses
    mm <- MM(as.matrix(log(d_seq + 1)), as.matrix(d_array))
    b0 <- mm$betamat[,1] + mm$betahat[1]; b1 <- mm$betamat[,2] + mm$betahat[2]
    sweep(sweep(log(d_seq + 1), 1, b1, "*"), 1, b0, "+")
  }
)

# ---- 5. published values to match --------------------------------------
load("d_plot_Type_I_error_small.rda")
target <- d_plot[d_plot$method == "MMR", ]

CONDS <- c("balanced", "same_imbalance", "opp_imbalance", "half_imbalance")
SEEDS <- 101:103

out <- list()
for (cond in CONDS) {
  for (sd in SEEDS) {
    res <- sim_array_seq_conditions(m = 20, n_case_bal = 10, n_case_imb = 13,
                                    condition = cond, n_DE = 0, seed = sd)
    d_array <- res$sim_array; d_seq <- res$sim_seq
    pub <- target$Type_I_error[target$balance == cond & target$seed == sd]
    row <- data.frame(condition = cond, seed = sd, published = pub)
    for (nm in names(variants)) {
      v <- tryCatch({
        ds <- variants[[nm]](d_array, d_seq)
        ds <- as.data.frame(ds)
        rownames(ds) <- rownames(d_seq); colnames(ds) <- colnames(d_seq)
        Type_I_error_Power(as.data.frame(d_array), ds)$Type_I_error
      }, error = function(e) NA_real_)
      row[[nm]] <- v
    }
    out[[length(out) + 1]] <- row
    cat(sprintf("%-16s seed %d  published=%.9f\n", cond, sd, pub)); flush.console()
  }
}
tab <- do.call(rbind, out)

cat("\n================ MMR variant vs published ================\n")
print(tab, row.names = FALSE, digits = 9)

cat("\n================ |variant - published| ================\n")
d <- tab
for (nm in names(variants)) d[[nm]] <- abs(tab[[nm]] - tab$published)
print(d[, c("condition","seed", names(variants))], row.names = FALSE, digits = 3)

cat("\n================ verdict ================\n")
for (nm in names(variants)) {
  mx <- max(abs(tab[[nm]] - tab$published), na.rm = TRUE)
  cat(sprintf("%-22s max |diff| = %.3e  %s\n", nm, mx,
              if (is.finite(mx) && mx < 1e-9) "  <-- MATCHES PUBLISHED" else ""))
}
write.csv(tab, file.path(ROOT, "mmr_fingerprint_results.csv"), row.names = FALSE)
